services:
  birthday-bot:
    container_name: birthday-bot
    image: birthday-bot
    build: .
    restart: always
    env_file: 
      - .envrc
    volumes:
      - ./birthdays.json:/app/birthdays.json  # Mount the JSON file for persistent data
      - ./bot.log:/app/bot.log  # Mount the log file for persistent logging
    command: python bot.py